name: Publish to GitHub Packages

# On tag push
on:
  workflow_dispatch: # for manual trigger
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Get Token
        id: get_actions_token
        uses: nominal-io/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 # v4.0.1
        with:
          application_id: ${{secrets.NOMBOT_APP_ID}}
          application_private_key: ${{secrets.NOMBOT_PRIVATE_KEY}}
          permissions: 'contents:read, packages:write'
          revoke_token: true

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nominal-io'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Run tests
        run: npm test
        env:
          MOCHA_THROW_DEPRECATION: false

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ steps.get_actions_token.outputs.token }}
